### ISSUE TITLE
Terraforged and rankine crash

### ISSUE THREAD

**Issue by DoodlyDrawn** [CannoliCatfish/project-rankine#265]
while creating new world

`---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 3/10/22, 7:43 PM
Description: generating features & structures (TerraForged World-Gen)

com.terraforged.mod.profiler.watchdog.UncheckedException: Critical error detected whilst generating Feature [rankine:ore_intrusion]
Caused by: java.lang.IllegalStateException: Tag rankine:intrusion_passable used before it was bound
	at net.minecraft.tags.TagRegistry$NamedTag.func_232944_c_(TagRegistry.java:131) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.tags.TagRegistry$NamedTag.func_230235_a_(TagRegistry.java:142) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.block.Block.func_203417_a(Block.java:115) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:snowrealmagic.mixins.json:MixinBlock,pl:mixin:APP:dankstorage.mixins.json:MixinBlock,pl:mixin:APP:survive.mixins.json:BlockMixin,pl:mixin:APP:autumnity.mixins.json:BlockMixin,pl:mixin:APP:roadrunner.mixins.json:ai.pathing.MixinBlock,pl:mixin:APP:roadrunner.mixins.json:shapes.blockstate_cache.BlockMixin,pl:mixin:APP:kubejs-common.mixins.json:BlockMixin,pl:mixin:A}
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_235714_a_(AbstractBlock.java:686) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,re:classloading,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,pl:mixin:APP:ferritecore.blockstatecache.mixin.json:AbstractBlockStateMixin,pl:mixin:APP:betterweather.mixins.json:block.MixinAbstractBlockState,pl:mixin:APP:starlight.mixins.json:common.blockstate.AbstractBlockStateMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.AbstractBlockStateMixin,pl:mixin:APP:kubejs-common.mixins.json:BlockStateBaseMixin,pl:mixin:APP:roadrunner.mixins.json:ai.pathing.MixinAbstractBlockState,pl:mixin:APP:roadrunner.mixins.json:block.flatten_states.AbstractBlockStateMixin,pl:mixin:A}
	at com.cannolicatfish.rankine.world.gen.feature.IntrusionFeature.generate(IntrusionFeature.java:106) ~[rankine:1.16.5-1.3.1] {re:classloading}
	at com.cannolicatfish.rankine.world.gen.feature.IntrusionFeature.func_241855_a(IntrusionFeature.java:23) ~[rankine:1.16.5-1.3.1] {re:classloading}
	at net.minecraft.world.gen.feature.ConfiguredFeature.func_242765_a(SourceFile:55) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.world.gen.feature.DecoratedFeature.func_242772_a(SourceFile:23) ~[?:?] {re:classloading}
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?] {}
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658) ~[?:?] {}
	at net.minecraft.world.gen.feature.DecoratedFeature.func_241855_a(SourceFile:22) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.DecoratedFeature.func_241855_a(SourceFile:14) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.ConfiguredFeature.func_242765_a(SourceFile:55) ~[?:?] {re:classloading,re:mixin}
	at com.terraforged.mod.chunk.generator.FeatureGenerator.decorate(FeatureGenerator.java:166) ~[terraforged:1.16.5-0.2.15] {re:classloading}
	at com.terraforged.mod.chunk.generator.FeatureGenerator.decorate(FeatureGenerator.java:106) ~[terraforged:1.16.5-0.2.15] {re:classloading}
	at com.terraforged.mod.chunk.generator.FeatureGenerator.generateFeatures(FeatureGenerator.java:88) ~[terraforged:1.16.5-0.2.15] {re:classloading}
	at com.terraforged.mod.chunk.TFChunkGenerator.func_230351_a_(TFChunkGenerator.java:250) ~[terraforged:1.16.5-0.2.15] {re:classloading}
	at net.minecraft.world.chunk.ChunkStatus.func_222605_b(ChunkStatus.java:77) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:worldgenerationprofiler:ChunkStatus#doGenerationWork,re:classloading,pl:accesstransformer:B,xf:fml:worldgenerationprofiler:ChunkStatus#doGenerationWork,pl:mixin:APP:bettercaves.mixins.json:ChunkStatusMixin,pl:mixin:A}
	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:198) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:worldgenerationprofiler:ChunkStatus#doGenerationWork,re:classloading,pl:accesstransformer:B,xf:fml:worldgenerationprofiler:ChunkStatus#doGenerationWork,pl:mixin:APP:bettercaves.mixins.json:ChunkStatusMixin,pl:mixin:A}
	at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManager.java:524) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kryptonreforged.mixins.json:network.shared.flushconsolidation.ThreadedAnvilChunkStorageMixin,pl:mixin:APP:betterweather.mixins.json:access.ChunkManagerAccess,pl:mixin:APP:chunksavingfix.mixins.json:MixinChunkManager,pl:mixin:APP:ftbchunks-common.mixins.json:ChunkMapMixin,pl:mixin:APP:roadrunner.mixins.json:world.chunk_ticking.ThreadedAnvilChunkStorageMixin,pl:mixin:APP:roadrunner.mixins.json:world.player_chunk_tick.ThreadedAnvilChunkStorageMixin,pl:mixin:A}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
	at net.minecraft.world.server.ChunkManager.lambda$scheduleChunkGeneration$20(ChunkManager.java:522) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kryptonreforged.mixins.json:network.shared.flushconsolidation.ThreadedAnvilChunkStorageMixin,pl:mixin:APP:betterweather.mixins.json:access.ChunkManagerAccess,pl:mixin:APP:chunksavingfix.mixins.json:MixinChunkManager,pl:mixin:APP:ftbchunks-common.mixins.json:ChunkMapMixin,pl:mixin:APP:roadrunner.mixins.json:world.chunk_ticking.ThreadedAnvilChunkStorageMixin,pl:mixin:APP:roadrunner.mixins.json:world.player_chunk_tick.ThreadedAnvilChunkStorageMixin,pl:mixin:A}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?] {}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:roadrunner.mixins.json:world.chunk_task_system.ChunkTaskPrioritySystemMixin,pl:mixin:A}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:94) [?:?] {re:mixin,re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:137) [?:?] {re:mixin,re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:105) [?:?] {re:mixin,re:classloading}
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1429) [?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) [?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) [?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) [?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) [?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Current Chunk --
Details:
	Pos: [27, 282]
	Status: liquid_carvers
	Structure Starts: [appliedenergistics2:meteorite, minecraft:mineshaft, minecraft:pillager_outpost, minecraft:ruined_portal, minecraft:stronghold, minecraft:village, mysticalworld:barrow, mysticalworld:hut, mysticalworld:ruined_hut, quark:big_dungeon]
	Structure Refs: [atmospheric:arid_shrine, autumnity:maple_witch_hut, betterendforge:eternal_portal_structure, betterendforge:giant_ice_star_structure, betterendforge:giant_mossy_glowshroom_structure, betterendforge:megalake_small_structure, betterendforge:megalake_structure, betterendforge:mountain_structure, betterendforge:painted_mountain_structure, betternether:city, endrem:ancient_witch_hut, endrem:end_castle, endrem:end_gate, infernalexp:bastion_outpost, infernalexp:glowstone_canyon_ruin, infernalexp:soul_sand_valley_ruin, infernalexp:strider_altar, minecraft:bastion_remnant, minecraft:buried_treasure, minecraft:desert_pyramid, minecraft:endcity, minecraft:fortress, minecraft:igloo, minecraft:jungle_pyramid, minecraft:mansion, minecraft:mineshaft, minecraft:monument, minecraft:nether_fossil, minecraft:ocean_ruin, minecraft:pillager_outpost, minecraft:ruined_portal, minecraft:shipwreck, minecraft:stronghold, minecraft:swamp_hut, minecraft:village, mysticalworld:barrow, mysticalworld:hut, mysticalworld:ruined_hut, outer_end:catacombs, outer_end:end_tower, quark:big_dungeon, vanillaboom:nether_well]

-- TerraForged ChunkGenerator --
Details:
	Seed: 831340867
	Settings: {"miscellaneous":{"smoothLayerDecorator":true,"strataRegionSize":600,"strataDecorator":true,"oreCompatibleStoneOnly":true,"erosionDecorator":true,"plainStoneErosion":false,"naturalSnowDecorator":true,"customBiomeFeatures":true,"vanillaLakes":false,"vanillaSprings":true,"vanillaLavaLakes":true,"vanillaLavaSprings":true,"mountainBiomeUsage":0.4,"volcanoBiomeUsage":0.4},"dimensions":{"bedrockLayer":{"material":"minecraft:bedrock","minDepth":1,"variance":0},"dimensions":{"nether":"infernalexp:compat_world_type","end":"betterendforge:world_type","includeExtraDimensions":true}},"structures":{"stronghold":{"distance":32,"spread":3,"count":128,"salt":0,"constrainToBiomes":false,"disabled":false},"structures":{"appliedenergistics2:meteorite":{"spacing":32,"separation":8,"salt":124895656,"disabled":false},"atmospheric:arid_shrine":{"spacing":32,"separation":8,"salt":304972544,"disabled":false},"autumnity:maple_witch_hut":{"spacing":32,"separation":8,"salt":56181420,"disabled":false},"betternether:city":{"spacing":64,"separation":32,"salt":1234567936,"disabled":false},"infernalexp:bastion_outpost":{"spacing":3,"separation":1,"salt":720435968,"disabled":false},"infernalexp:glowstone_canyon_ruin":{"spacing":1,"separation":0,"salt":20394856,"disabled":false},"infernalexp:soul_sand_valley_ruin":{"spacing":4,"separation":2,"salt":29456392,"disabled":false},"infernalexp:strider_altar":{"spacing":10,"separation":5,"salt":80837592,"disabled":false},"minecraft:bastion_remnant":{"spacing":27,"separation":4,"salt":30084232,"disabled":false},"minecraft:buried_treasure":{"spacing":1,"separation":0,"salt":0,"disabled":false},"minecraft:desert_pyramid":{"spacing":32,"separation":8,"salt":14357617,"disabled":false},"minecraft:endcity":{"spacing":20,"separation":11,"salt":10387313,"disabled":false},"minecraft:fortress":{"spacing":27,"separation":4,"salt":30084232,"disabled":false},"minecraft:igloo":{"spacing":32,"separation":8,"salt":14357618,"disabled":false},"minecraft:jungle_pyramid":{"spacing":32,"separation":8,"salt":14357619,"disabled":false},"minecraft:mansion":{"spacing":80,"separation":20,"salt":10387319,"disabled":false},"minecraft:mineshaft":{"spacing":1,"separation":0,"salt":0,"disabled":false},"minecraft:monument":{"spacing":32,"separation":5,"salt":10387313,"disabled":false},"minecraft:nether_fossil":{"spacing":2,"separation":1,"salt":14357921,"disabled":false},"minecraft:ocean_ruin":{"spacing":20,"separation":8,"salt":14357621,"disabled":false},"minecraft:pillager_outpost":{"spacing":32,"separation":8,"salt":165745296,"disabled":false},"minecraft:ruined_portal":{"spacing":40,"separation":15,"salt":34222644,"disabled":false},"minecraft:shipwreck":{"spacing":24,"separation":4,"salt":165745296,"disabled":false},"minecraft:stronghold":{"spacing":1,"separation":0,"salt":0,"disabled":false},"minecraft:swamp_hut":{"spacing":32,"separation":8,"salt":14357620,"disabled":false},"minecraft:village":{"spacing":32,"separation":8,"salt":10387312,"disabled":false},"mysticalworld:barrow":{"spacing":150,"separation":65,"salt":314159232,"disabled":false},"mysticalworld:hut":{"spacing":45,"separation":20,"salt":12886419,"disabled":false},"mysticalworld:ruined_hut":{"spacing":70,"separation":35,"salt":8266497,"disabled":false},"quark:big_dungeon":{"spacing":20,"separation":11,"salt":79234824,"disabled":false}}},"world":{"continent":{"continentType":"MULTI","continentShape":"EUCLIDEAN","continentScale":3000,"continentJitter":0.699},"controlPoints":{"deepOcean":0.1,"shallowOcean":0.25,"beach":0.326,"coast":0.448,"inland":0.5},"properties":{"spawnType":"CONTINENT_CENTER","worldHeight":256,"seaLevel":63}},"climate":{"temperature":{"seedOffset":0,"scale":6,"falloff":2,"min":0.0,"max":0.98,"bias":0.05},"moisture":{"seedOffset":0,"scale":6,"falloff":1,"min":0.0,"max":1.0,"bias":0.0},"biomeShape":{"biomeSize":225,"macroNoiseSize":8,"biomeWarpScale":150,"biomeWarpStrength":80},"biomeEdgeShape":{"type":"SIMPLEX","scale":24,"octaves":2,"gain":0.5,"lacunarity":2.65,"strength":14}},"terrain":{"general":{"terrainSeedOffset":0,"terrainRegionSize":1200,"globalVerticalScale":0.98,"globalHorizontalScale":1.0,"fancyMountains":true},"steppe":{"weight":1.0,"baseScale":1.0,"verticalScale":1.0,"horizontalScale":1.0},"plains":{"weight":2.0,"baseScale":1.0,"verticalScale":1.0,"horizontalScale":1.0},"hills":{"weight":2.0,"baseScale":1.0,"verticalScale":1.0,"horizontalScale":1.0},"dales":{"weight":1.5,"baseScale":1.0,"verticalScale":1.0,"horizontalScale":1.0},"plateau":{"weight":1.5,"baseScale":1.0,"verticalScale":1.0,"horizontalScale":1.0},"badlands":{"weight":1.0,"baseScale":1.0,"verticalScale":1.0,"horizontalScale":1.0},"torridonian":{"weight":2.0,"baseScale":1.0,"verticalScale":1.0,"horizontalScale":1.0},"mountains":{"weight":2.5,"baseScale":1.0,"verticalScale":1.0,"horizontalScale":1.0},"volcano":{"weight":5.0,"baseScale":1.0,"verticalScale":1.0,"horizontalScale":1.0}},"rivers":{"seedOffset":0,"riverCount":8,"mainRivers":{"bedDepth":6,"minBankHeight":2,"maxBankHeight":6,"bedWidth":8,"bankWidth":30,"fade":0.3},"branchRivers":{"bedDepth":4,"minBankHeight":1,"maxBankHeight":4,"bedWidth":5,"bankWidth":14,"fade":0.975},"lakes":{"chance":0.3,"minStartDistance":0.0,"maxStartDistance":0.017,"depth":10,"sizeMin":75,"sizeMax":249,"minBankHeight":2,"maxBankHeight":10},"wetlands":{"chance":0.6,"sizeMin":175,"sizeMax":225}},"filters":{"erosion":{"dropletsPerChunk":135,"dropletLifetime":12,"dropletVolume":0.699,"dropletVelocity":0.699,"erosionRate":0.5,"depositeRate":0.5},"smoothing":{"iterations":1,"smoothingRadius":1.799,"smoothingRate":0.898}}}

-- TerraForged BiomeProvider --
Details:
	Overworld Biomes: [minecraft:badlands, minecraft:badlands_plateau, minecraft:bamboo_jungle, bayou_blues:bayou, minecraft:beach, minecraft:birch_forest, environmental:blossom_highlands, environmental:blossom_valleys, environmental:blossom_woods, terraforged:bryce, terraforged:cold_marshland, minecraft:cold_ocean, terraforged:cold_steppe, minecraft:dark_forest, minecraft:deep_cold_ocean, minecraft:deep_frozen_ocean, minecraft:deep_lukewarm_ocean, minecraft:deep_ocean, minecraft:deep_warm_ocean, minecraft:desert, minecraft:desert_lakes, atmospheric:dunes, minecraft:eroded_badlands, terraforged:fir_forest, atmospheric:flourishing_dunes, minecraft:flower_forest, terraforged:flower_plains, minecraft:forest, terraforged:frozen_lake, terraforged:frozen_marsh, minecraft:frozen_ocean, minecraft:frozen_river, minecraft:giant_spruce_taiga, minecraft:giant_tree_taiga, minecraft:gravelly_mountains, atmospheric:hot_springs, minecraft:ice_spikes, minecraft:jungle, minecraft:jungle_edge, terraforged:lake, abundance:lavender_fields, abundance:lavender_forest, minecraft:lukewarm_ocean, terraincognita:lush_plains, autumnity:maple_forest, environmental:marsh, terraforged:marshland, integrateddynamics:meneglin, minecraft:modified_badlands_plateau, minecraft:modified_gravelly_mountains, minecraft:modified_jungle, minecraft:modified_jungle_edge, minecraft:modified_wooded_badlands_plateau, minecraft:mountains, minecraft:mushroom_field_shore, minecraft:mushroom_fields, environmental:mushroom_marsh, terraincognita:muskeg, abundance:nemophila_fields, minecraft:ocean, autumnity:orange_spotted_dark_forest, atmospheric:petrified_dunes, minecraft:plains, autumnity:pumpkin_fields, atmospheric:rainforest, atmospheric:rainforest_basin, atmospheric:rainforest_mountains, atmospheric:rainforest_plateau, autumnity:red_spotted_taiga, minecraft:river, atmospheric:rocky_dunes, minecraft:savanna, minecraft:savanna_plateau, terraforged:savanna_scrub, minecraft:shattered_savanna, minecraft:shattered_savanna_plateau, terraforged:shattered_savanna_scrub, minecraft:snowy_beach, terraforged:snowy_fir_forest, minecraft:snowy_mountains, minecraft:snowy_taiga, minecraft:snowy_taiga_mountains, minecraft:snowy_tundra, atmospheric:sparse_rainforest_basin, atmospheric:sparse_rainforest_plateau, terraforged:steppe, terraforged:stone_forest, minecraft:stone_shore, minecraft:sunflower_plains, minecraft:swamp, minecraft:taiga, minecraft:taiga_mountains, terraforged:taiga_scrub, minecraft:tall_birch_forest, terraforged:warm_beach, minecraft:warm_ocean, minecraft:wooded_badlands_plateau, minecraft:wooded_mountains, autumnity:yellow_spotted_forest]

-- TerraForged Biome Weights Config --
Details:
	terraforged:example_biome: 10

-- TerraForged Profiler --
Details:
	Timings: 
		Section             Count      Time MS    Min MS     Max MS     Average MS
		structure_starts    547        7776       0          7639       14.22
		structure_refs      50         22         0          4          0.44
		biomes              36         810        0          668        22.50
		terrain             21         652        2          124        31.05
		surface             9          152        3          84         16.89
		air_carvers         9          985        11         509        109.44
		fluid_carvers       9          0          0          0          0.00
		decoration          1          533        533        533        533.00
		mob_spawns          0          0          0          0          0.00
		structure_searches  0          0          0          0          0.00
		Sum                                                             727.54

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 15.0.2, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), AdoptOpenJDK
	Memory: 1520698488 bytes (1450 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 4
	JVM Flags: 11 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+IgnoreUnrecognizedVMOptions -Xmx4G -Xms4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.20.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.20.jar runtime_enum_extender PLUGINSERVICE 
		/forge-1.16.5-36.2.20.jar capability_inject_definalize PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.20.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.20.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.20
	FML Language Providers: 
		javafml@36.2
		minecraft@1
		kotlinforforge@1.16.0
		scorge@3.1.3
`

terraforged notes that this is an issue with intrusions by rankine.
i've also placed terraforged and rankine only afterwards, oddly enough it works

**Comment by DoodlyDrawn** [comment]
i should add that terraforged worked without much issue with rankine 1.2.3 hotfix 3

**Comment by DoodlyDrawn** [comment]
notice that i have "not enough crashes"
tested without terraforged, with quark realistic worldgen, it crashed once, after i generated a default world type, i was able to generate quark realistic

**Comment by DoodlyDrawn** [comment]
i found the issue, apparently i put th previous tags of rankine 1.2.3 hotfix 3 in the openloader datapack, this caused the issue with terraforged, deleting the tags from the datapack, or replacing it with the newer version resolved the issue
